---
- name: Check if CVEs are available (individually)
  register: cve_status
  changed_when: false
  failed_when: cve_status.rc != 0 and cve_status.rc != 100
  ansible.builtin.shell: "{{ ansible_facts['pkg_mgr'] }} check-update --cve {{ item }}"

- name: Add CVE to report
  when: cve_status.rc == 100
  delegate_to: localhost
  block:
    - name: Checks CVE details to public API
      ansible.builtin.uri:
        url: "https://access.redhat.com/hydra/rest/securitydata/cve/{{ item }}.xml"
        return_content: true
      register: cve_detail
      delegate_to: "{{ satellite_host }}"
      run_once: true

    - name: Gets severity from CVE
      community.general.xml:
        xmlstring: "{{ cve_detail.content }}"
        xpath: /Vulnerability/ThreatSeverity
        content: text
      register: cve_severity
      run_once: true

    - ansible.builtin.lineinfile:
        path: "files/{{ tarea_sga }}-report-{{ current_date }}.csv"
        line: "{{ ansible_facts['fqdn'] }},{{ item }},{{ cve_severity.matches[0].ThreatSeverity }},{{ current_date }}"

